# Generated by Django 4.2.7 on 2024-06-28 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_index', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('image_in_question', models.BooleanField(default=False)),
                ('q_image_description', models.TextField(blank=True, null=True)),
                ('image_in_answers', models.BooleanField(default=False)),
                ('english_question', models.TextField()),
                ('english_answer1', models.TextField()),
                ('english_answer2', models.TextField()),
                ('english_answer3', models.TextField()),
                ('description_of_answer_image1', models.TextField(blank=True, null=True)),
                ('description_of_answer_image2', models.TextField(blank=True, null=True)),
                ('description_of_answer_image3', models.TextField(blank=True, null=True)),
                ('v_text', models.TextField()),
                ('v_image_steps', models.TextField()),
                ('a_text', models.TextField()),
                ('k_text', models.TextField()),
                ('sinhala_question', models.TextField(blank=True, null=True)),
                ('sinhala_answer1', models.TextField(blank=True, null=True)),
                ('sinhala_answer2', models.TextField(blank=True, null=True)),
                ('sinhala_answer3', models.TextField(blank=True, null=True)),
                ('sinhala_v_text', models.TextField(blank=True, null=True)),
                ('sinhala_v_image_steps', models.TextField(blank=True, null=True)),
                ('sinhala_a_text', models.TextField(blank=True, null=True)),
                ('sinhala_k_text', models.TextField(blank=True, null=True)),
                ('tamil_question', models.TextField(blank=True, null=True)),
                ('tamil_answer1', models.TextField(blank=True, null=True)),
                ('tamil_answer2', models.TextField(blank=True, null=True)),
                ('tamil_answer3', models.TextField(blank=True, null=True)),
                ('tamil_v_text', models.TextField(blank=True, null=True)),
                ('tamil_v_image_steps', models.TextField(blank=True, null=True)),
                ('tamil_a_text', models.TextField(blank=True, null=True)),
                ('tamil_k_text', models.TextField(blank=True, null=True)),
                ('question_image_illustration', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('answer1_image_illustration', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('answer2_image_illustration', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('answer3_image_illustration', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('visual_instructions_illustration', models.ImageField(blank=True, null=True, upload_to='illustrations/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('incomplete', 'Incomplete'), ('approved', 'Approved')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
