# Generated by Django 5.0.6 on 2024-08-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_question_status_question_illustrator_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sinhala_v_image_steps',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tamil_v_image_steps',
        ),
    ]
